version: "3.7"
services:
  db:
    container_name: sourcepad-be-db
    image: postgres:10.13-alpine
    user: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - data:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"

volumes:
  data:
  redis:
