default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: sourcepad_be_test_development

test:
  <<: *default
  database: sourcepad_be_test_test

production:
  <<: *default
  database: sourcepad_be_test_production
  username: sourcepad_be_test
  password: <%= ENV["SOURCEPAD_BE_TEST_DATABASE_PASSWORD"] %>
